### ISSUE TITLE
[Feature Request] Support Leatrix Plus enhanced quest log

### ISSUE THREAD

**Issue by Bonkeybee** [MotherGinger/RecklessAbandon#22]
The buttons for abandoning a quest don't show up for quest frames that show more than the normal amount of quests.

![image](https://user-images.githubusercontent.com/9619823/120087852-4ee05080-c0b1-11eb-8918-fb286e14cb7f.png)

**Comment by MotherGinger** [comment]
Thank you for reaching out, this has been implemented in [v1.1.0](https://www.curseforge.com/wow/addons/reckless-abandon/files), enjoy!
