### ISSUE TITLE
[Bug Report] addon abandons zone quest other than selected one

### ISSUE THREAD

**Issue by comiluv** [MotherGinger/RecklessAbandon#24]
**Describe the bug**
When the user clicks on X icon next to a zone displayed in the world map to abandon quest from that zone, quest from different zone is abandoned.

**To Reproduce**
1. Open world map
2. Click on X icon next to a zone
3. Click on okay when the prompt appears

**Expected behavior**
Quests from the selected zone are abandoned

**Screenshots**
n/a

**Additional context**
Locale: koKR

**Comment by MotherGinger** [comment]
I will take a look at this, thanks for the report!

**Comment by MotherGinger** [comment]
I believe this could be due to the koKR localization, it may be causing the buttons to render closer or farther apart, creating overlap so it might make it so when you click one abandon button it accidently clicks another.

I will try to test this on koKR to verify, thanks for the patience!

**Comment by MotherGinger** [comment]
This is fixed in the next release, the abandon buttons have had their interaction areas redrawn, this should avoid overlap and issues with the wrong buttons being selected or buttons being unclickable
