### ISSUE TITLE
Error on Reloading UI

### ISSUE THREAD

**Issue by griddark** [MotherGinger/RecklessAbandon#25]
6x Interface/AddOns/RecklessAbandon/Core/Core.lua:255: attempt to index field 'campaignQuests' (a nil value)
[string "@Interface/AddOns/RecklessAbandon/Core/Core.lua"]:255: in function <Interface/AddOns/RecklessAbandon/Core/Core.lua:251>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:239: in function `SaveCacheOnCVar'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:339: in function `SaveData'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:895: in function `eventCallbackFunc'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:904: in function <...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:902>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 frameType = "Button"
 ReleaseAll = <function> defined @Interface/SharedXML/Pools.lua:74
 activeObjects = <table> {
 }
 GetNextInactive = <function> defined @Interface/SharedXML/Pools.lua:92
 creationFunc = <function> defined @Interface/SharedXML/Pools.lua:116
 EnumerateActive = <function> defined @Interface/SharedXML/Pools.lua:84
 SetResetDisallowedIfNew = <function> defined @Interface/SharedXML/Pools.lua:80
 GetTemplate = <function> defined @Interface/SharedXML/Pools.lua:153
 OnLoad = <function> defined @Interface/SharedXML/Pools.lua:124
 frameTemplate = "RECKLESS_GROUP_ABANDON_BUTTON"
 IsActive = <function> defined @Interface/SharedXML/Pools.lua:96
 GetNumActive = <function> defined @Interface/SharedXML/Pools.lua:100
 resetterFunc = <function> defined @Interface/SharedXML/Pools.lua:161
 parent = QuestScrollFrame {
 }
 numActiveObjects = 0
 inactiveObjects = <table> {
 }
 Release = <function> defined @Interface/SharedXML/Pools.lua:59
 Acquire = <function> defined @Interface/SharedXML/Pools.lua:40
 GetNextActive = <function> defined @Interface/SharedXML/Pools.lua:88
 EnumerateInactive = <function> defined @Interface/SharedXML/Pools.lua:104
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'campaignQuests' (a nil value)"
questButtonPool = <table> {
 frameType = "Button"
 ReleaseAll = <function> defined @Interface/SharedXML/Pools.lua:74
 activeObjects = <table> {
 }
 GetNextInactive = <function> defined @Interface/SharedXML/Pools.lua:92
 creationFunc = <function> defined @Interface/SharedXML/Pools.lua:116
 EnumerateActive = <function> defined @Interface/SharedXML/Pools.lua:84
 SetResetDisallowedIfNew = <function> defined @Interface/SharedXML/Pools.lua:80
 GetTemplate = <function> defined @Interface/SharedXML/Pools.lua:153
 OnLoad = <function> defined @Interface/SharedXML/Pools.lua:124
 frameTemplate = "RECKLESS_ABANDON_BUTTON"
 IsActive = <function> defined @Interface/SharedXML/Pools.lua:96
 GetNumActive = <function> defined @Interface/SharedXML/Pools.lua:100
 resetterFunc = <function> defined @Interface/SharedXML/Pools.lua:161
 parent = QuestScrollFrame {
 }
 numActiveObjects = 0
 inactiveObjects = <table> {
 }
 Release = <function> defined @Interface/SharedXML/Pools.lua:59
 Acquire = <function> defined @Interface/SharedXML/Pools.lua:40
 GetNextActive = <function> defined @Interface/SharedXML/Pools.lua:88
 EnumerateInactive = <function> defined @Interface/SharedXML/Pools.lua:104
}
groupButtonPool = <table> {
 frameType = "Button"
 ReleaseAll = <function> defined @Interface/SharedXML/Pools.lua:74
 activeObjects = <table> {
 }
 GetNextInactive = <function> defined @Interface/SharedXML/Pools.lua:92
 creationFunc = <function> defined @Interface/SharedXML/Pools.lua:116
 EnumerateActive = <function> defined @Interface/SharedXML/Pools.lua:84
 SetResetDisallowedIfNew = <function> defined @Interface/SharedXML/Pools.lua:80
 GetTemplate = <function> defined @Interface/SharedXML/Pools.lua:153
 OnLoad = <function> defined @Interface/SharedXML/Pools.lua:124
 frameTemplate = "RECKLESS_GROUP_ABANDON_BUTTON"
 IsActive = <function> defined @Interface/SharedXML/Pools.lua:96
 GetNumActive = <function> defined @Interface/SharedXML/Pools.lua:100
 resetterFunc = <function> defined @Interface/SharedXML/Pools.lua:161
 parent = QuestScrollFrame {
 }
 numActiveObjects = 0
 inactiveObjects = <table> {
 }
 Release = <function> defined @Interface/SharedXML/Pools.lua:59
 Acquire = <function> defined @Interface/SharedXML/Pools.lua:40
 GetNextActive = <function> defined @Interface/SharedXML/Pools.lua:88
 EnumerateInactive = <function> defined @Interface/SharedXML/Pools.lua:104
}
E = <table> {
 IsRetail = true
 mylevel = 60
 resolution = "3440x1440"
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:147

Reload UI

**Comment by MotherGinger** [comment]
Thanks for the report, looking into this now

**Comment by MotherGinger** [comment]
I am able to reproduce this, seems likely due to the recent API changes in the prepatch

So far in my testing, outside of the initial lua error, I am not seeing any other impact to functionality.

While I continue to work on a fix, please let me know if you notice any other impact related to this
